type Provider={id:string;kind:string;model:string;enabled:number;checks?:{mode:string;ok:number;error:string;error_type:string;tested_at:number;duration_ms:number}[]};
type Config={enabled:boolean;chatProviders:string[];speechProvider:string;speechModel:string;speechVoice:string};
type Panel={config:Config;providers:Provider[];shell:(s:string)=>void;api:(path:string,method?:string,data?:unknown)=>Promise<any>;load:()=>Promise<void>;saveConfig:()=>Promise<void>;notify:(s:string,error?:boolean)=>void};
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);
const field=(label:string,id:string,value:unknown,type="text")=>`<label>${esc(label)}<input id="${id}" type="${type}" value="${esc(value)}" autocomplete="${type==="password"?"new-password":"off"}"></label>`;
const val=(id:string)=>(document.getElementById(id) as HTMLInputElement).value;
const defaults:Record<string,{id:string;model:string;voice:string;mode:string}>={
  cloudflare:{id:"cloudflare-free",model:"@cf/meta/llama-3.1-8b-instruct-fp8",voice:"en",mode:"chat"},
  groq:{id:"groq-main",model:"llama-3.3-70b-versatile",voice:"",mode:"chat"},
  gemini:{id:"gemini-speech",model:"gemini-3.8-flash-lite-tts",voice:"Kore",mode:"speech"},
  elevenlabs:{id:"elevenlabs-speech",model:"eleven_multilingual_v2",voice:"",mode:"speech"},
  fish:{id:"fish-speech",model:"s2.1-pro-free",voice:"",mode:"speech"},
};
let activePreview:HTMLAudioElement|undefined;
export function stopProviderPreview(){if(activePreview){activePreview.pause();activePreview.removeAttribute("src");activePreview.load();activePreview=undefined;}}
document.addEventListener("visibilitychange",()=>{if(document.hidden)stopProviderPreview();});
export function renderProviders(p:Panel) {
  const {config,providers}=p;
  p.shell(`<div class="heading"><h1>Providers, with proof.</h1><p>Send a short real request before saving a key or model. Keys remain encrypted on the backend.</p></div>
  <article class="testing-help"><h3>Free testing</h3><p>Cloudflare uses your connected free AI allowance without a key. Groq has model/account rate limits. Fish <code>s2.1-pro-free</code> is the free speech model; other Fish models are billed. ElevenLabs uses your account's credits/eligibility.</p><button id="free-route">Use Cloudflare for chat</button><button id="route-test">Test KITTY’s chat route</button><pre id="route-result" role="status"></pre></article>
  <div class="two-col"><article><h3>Configured providers</h3>${providers.map(v=>`<div class="provider"><div><strong>${esc(v.id)}</strong><p>${esc(v.kind)} · ${esc(v.model)}</p><small>${v.kind==="cloudflare"?"No key required":"Key saved securely"} · ${v.enabled?"enabled":"paused"}</small>${(v.checks||[]).map(c=>`<p class="check-result ${c.ok?"pass":"fail"}">${c.ok?"Passed":"Failed"} · ${esc(c.mode)} · ${new Date(c.tested_at).toLocaleString()}${c.error?`<br>${esc(c.error)} <small>(${esc(c.error_type)})</small>`:""}</p>`).join("")}</div><div class="provider-actions"><button data-edit="${esc(v.id)}">Edit / test</button><button data-models="${esc(v.id)}">Models</button><button data-delete="${esc(v.id)}" class="danger">Remove</button></div></div>`).join("")||"<p>No providers yet.</p>"}<pre id="models"></pre></article>
  <article><h3>Add or update</h3><form id="provider-form">${field("Provider ID","provider-id","cloudflare-free")}<label>Provider<select id="kind"><option value="cloudflare">Cloudflare free AI</option><option value="groq">Groq</option><option value="gemini">Gemini</option><option value="elevenlabs">ElevenLabs</option><option value="fish">Fish Audio</option></select></label><label>Test type<select id="test-mode"><option value="chat">Streamed chat</option><option value="speech">Speech audio</option></select></label>${field("Model","model",defaults.cloudflare.model)}${field("Voice ID / language (speech only)","test-voice","en")}${field("API key · blank preserves a saved key","key","","password")}<label class="check"><input type="checkbox" id="provider-enabled" checked>Enabled</label><div class="form-actions"><button id="test-only" type="button">Test request</button><button type="submit" class="primary">Test & save</button></div><p class="hint">A test sends a fixed short greeting and may consume provider quota. Failed tests never overwrite the saved key.</p><pre id="test-result" role="status"></pre><audio id="test-audio" controls hidden></audio></form></article></div>
  <article><h3>Routing</h3><form id="routing">${field("Chat providers in order, separated by commas","order",config.chatProviders.join(","))}<label>Cloud speech provider<select id="speech-provider"><option value="">Disabled (device speech still works)</option>${providers.filter(v=>v.kind!=="groq").map(v=>`<option value="${esc(v.id)}" ${config.speechProvider===v.id?"selected":""}>${esc(v.id)} · ${esc(v.kind)}</option>`).join("")}</select></label>${field("Speech model","speech-model",config.speechModel)}${field("Voice ID / language","voice",config.speechVoice)}<p class="hint">Gemini: a voice such as Kore. Cloudflare: a language code such as en. ElevenLabs/Fish: your chosen voice ID from their dashboard. Chat fallbacks apply before any text arrives.</p><button type="submit" class="primary">Save routing</button></form></article>`);
  const set=(id:string,value:string)=>(document.getElementById(id) as HTMLInputElement).value=value;
  const updateKind=()=>{
    const d=defaults[val("kind")];set("provider-id",d.id);set("model",d.model);set("test-mode",d.mode);set("test-voice",d.voice);set("key","");
    (document.getElementById("key") as HTMLInputElement).disabled=val("kind")==="cloudflare";
  };
  updateKind();document.getElementById("kind")!.onchange=updateKind;
  document.getElementById("test-mode")!.onchange=()=>{if(val("kind")==="cloudflare"){const speech=val("test-mode")==="speech";set("model",speech?"@cf/myshell-ai/melotts":defaults.cloudflare.model);if(["cloudflare-free","cloudflare-speech"].includes(val("provider-id")))set("provider-id",speech?"cloudflare-speech":"cloudflare-free");}};
  async function runTest(save:boolean){
    const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>("#provider-form button"));buttons.forEach(b=>b.disabled=true);
    stopProviderPreview();const result=document.getElementById("test-result")!;result.textContent="Sending a real test request…";
    try {
      const r=await p.api("admin/providers/test","POST",{id:val("provider-id"),kind:val("kind"),model:val("model"),enabled:(document.getElementById("provider-enabled") as HTMLInputElement).checked,mode:val("test-mode"),voice:val("test-voice"),save,...(val("key")?{key:val("key")}: {})});
      result.textContent=r.ok?`Passed · ${r.durationMs} ms\n${r.preview||"Audio generated; play the preview below."}`:`Failed · ${r.error}\n${r.errorType?"Diagnostic: "+r.errorType:""}`;
      result.className=r.ok?"test-pass":"test-fail";
      if(r.audio){activePreview=document.getElementById("test-audio") as HTMLAudioElement;activePreview.src=`data:${r.audio.mimeType};base64,${r.audio.data}`;activePreview.hidden=false;}
      if(r.saved){set("key","");await p.load();p.notify("Test passed. Provider saved securely.");}
    }catch(e){result.textContent=(e as Error).message;result.className="test-fail";}finally{buttons.forEach(b=>b.disabled=false);}
  }
  document.getElementById("test-only")!.onclick=()=>void runTest(false);
  document.getElementById("provider-form")!.onsubmit=e=>{e.preventDefault();void runTest(true);};
  document.querySelectorAll<HTMLButtonElement>("[data-edit]").forEach(b=>b.onclick=()=>{const v=providers.find(v=>v.id===b.dataset.edit)!;set("kind",v.kind);set("provider-id",v.id);set("model",v.model);set("key","");set("test-mode",v.kind==="fish"||v.kind==="elevenlabs"||/tts|melotts/i.test(v.model)?"speech":"chat");set("test-voice",config.speechProvider===v.id?config.speechVoice:defaults[v.kind].voice);(document.getElementById("provider-enabled") as HTMLInputElement).checked=!!v.enabled;(document.getElementById("key") as HTMLInputElement).disabled=v.kind==="cloudflare";document.getElementById("provider-form")!.scrollIntoView({behavior:"smooth",block:"start"});});
  document.querySelectorAll<HTMLButtonElement>("[data-models]").forEach(b=>b.onclick=async()=>{b.disabled=true;try{document.getElementById("models")!.textContent=(await p.api(`admin/models?provider=${b.dataset.models}`)).join("\n");}catch(e){p.notify((e as Error).message,true);}finally{b.disabled=false;}});
  document.querySelectorAll<HTMLButtonElement>("[data-delete]").forEach(b=>b.onclick=async()=>{if(!confirm(`Remove ${b.dataset.delete}?`))return;try{await p.api(`admin/providers/${b.dataset.delete}`,"DELETE");await p.load();}catch(e){p.notify((e as Error).message,true);}});
  document.getElementById("speech-provider")!.onchange=()=>{const v=providers.find(v=>v.id===val("speech-provider"));if(!v)return;const d=defaults[v.kind];set("speech-model",v.kind==="cloudflare"?"@cf/myshell-ai/melotts":v.kind==="gemini"?defaults.gemini.model:v.model);set("voice",d.voice);};
  document.getElementById("routing")!.onsubmit=async e=>{e.preventDefault();try{config.chatProviders=val("order").split(",").map(v=>v.trim()).filter(Boolean);config.speechProvider=val("speech-provider");config.speechModel=val("speech-model");config.speechVoice=val("voice");await p.saveConfig();p.notify("Routing saved.");}catch(e){p.notify((e as Error).message,true);}};
  document.getElementById("free-route")!.onclick=async()=>{try{const free=providers.find(v=>v.kind==="cloudflare"&&v.model===defaults.cloudflare.model&&v.enabled);if(!free)throw Error("First test & save an enabled Cloudflare chat provider.");config.chatProviders=[free.id,...config.chatProviders.filter(v=>v!==free.id)];await p.saveConfig();await p.load();p.notify("Cloudflare is now the primary chat provider.");}catch(e){p.notify((e as Error).message,true);}};
  document.getElementById("route-test")!.onclick=async()=>{const b=document.getElementById("route-test") as HTMLButtonElement;const r=document.getElementById("route-result")!;b.disabled=true;r.textContent="Testing the complete deployed KITTY reply path…";try{const v=await p.api("admin/chat-test","POST",{});r.textContent=v.ok?`Passed · ${v.durationMs} ms\n${v.preview}`:`Failed · ${v.error}`;}catch(e){r.textContent=(e as Error).message;}finally{b.disabled=false;}};
}
